apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ template "skydive.fullname" . }}-agent"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "skydive.fullname" . }}
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "skydive.fullname" . }}
  template:
    metadata:
      annotations:
        productName: {{ .Chart.Name | quote }}
        productID: 8e6bdbcba44f46939c3d1c54447386b2
        productVersion: {{ .Chart.Version | quote }}
      labels:
        app: {{ template "skydive.fullname" . }}
        chart: {{ .Chart.Name | quote }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        tier: agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostPID: true
      hostIPC: true
      securityContext:
        runAsNonRoot: false
{{- with .Values.agent.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.agent.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.agent.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
{{- end }}
      hostNetwork: true
      {{- if and .Values.image.secretName (ne .Values.image.secretName "") }}
      imagePullSecrets:
      - name: {{ .Values.image.secretName | quote }}
      {{- end }}
      containers:
      - name: agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy | default "" | quote }}
        terminationMessagePolicy: FallbackToLogsOnError
        args:
        - agent
        - --listen=0.0.0.0:8081
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            port: 8081
            path: /api/status
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8081
            path: /api/status
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 10
{{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
        env:
        - name: SKYDIVE_ANALYZERS
          value: "{{ template "skydive.fullname" . }}-analyzer.{{ .Release.Namespace }}.svc:{{ .Values.analyzer.service.port }}"
        - name: SKYDIVE_FLOW_PROTOCOL
          value: websocket
        - name: SKYDIVE_FLOW_DEFAULT_LAYER_KEY_MODE
          value: L3
        - name: SKYDIVE_AGENT_TOPOLOGY_PROBES
          value: {{ .Values.agent.topology.probes | quote }}
        - name: SKYDIVE_AGENT_TOPOLOGY_RUNC_RUN_PATH
          value: /var/run/runc /var/run/runc-ctrs /var/run/containerd/runc
{{- if and .Values.flowExporter.enabled .Values.flowExporter.env }}
{{ toYaml .Values.flowExporter.env | indent 8 }}
{{- end }}
      {{- with .Values.agent.env }}
{{ toYaml . | indent 8 }}
      {{- end }}
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            add: ["all"]
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
        - name: run
          mountPath: /host/run
        - name: ovsdb
          mountPath: /var/run/openvswitch/db.sock
        - name: runc
          mountPath: /var/run/runc
        - name: runc-ctrs
          mountPath: /var/run/runc-ctrs
        - name: containerd-runc
          mountPath: /var/run/containerd/runc
        - name: data-kubelet
          mountPath: /var/data/kubelet
        - name: lib-kubelet
          mountPath: /var/lib/kubelet
        - name: data-openshiftvolumes
          mountPath: /var/data/openshiftvolumes
        - name: lib-origin
          mountPath: /var/lib/origin
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      - name: run
        hostPath:
          path: /var/run/netns
      - name: ovsdb
        hostPath:
          path: /var/run/openvswitch/db.sock
      - name: runc
        hostPath:
          path: /var/run/runc
      - name: runc-ctrs
        hostPath:
          path: /var/run/runc-ctrs
      - name: containerd-runc
        hostPath:
          path: /var/run/containerd/runc
      - name: data-kubelet
        hostPath:
          path: /var/data/kubelet
      - name: lib-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: data-openshiftvolumes
        hostPath:
          path: /var/data/openshiftvolumes
      - name: lib-origin
        hostPath:
          path: /var/lib/origin
