apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "skydive.fullname" . }}-analyzer"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "skydive.fullname" . }}
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
imagePullSecrets:
  - name: "sa-{{ .Release.Namespace }}"
{{- if ne .Values.image.secretName "" }}
  - name: {{ .Values.image.secretName | quote }}
{{- end }}
