{{- if .Values.flowExporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "skydive.fullname" . }}-flow-exporter"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "skydive.fullname" . }}
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  accesskey: {{ .Values.flowExporter.write.s3.access_key | b64enc }}
  secretkey: {{ .Values.flowExporter.write.s3.secret_key | b64enc }}
  apikey: {{ .Values.flowExporter.write.s3.api_key | b64enc }}
{{- end }}
