{{- if .Values.flowExporter.enabled }}
apiVersion: apps/v1
kind: Deployment  # with ES bundled in, this would've been a StatefulSet, btw
metadata:
  name: "{{ template "skydive.fullname" . }}-flow-exporter"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "skydive.fullname" . }}
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "skydive.fullname" . }}
      chart: {{ .Chart.Name | quote }}
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      tier: flow-exporter
  template:
    metadata:
      annotations:
        productName: {{ .Chart.Name | quote }}
        productID: 8e6bdbcba44f46939c3d1c54447386b2
        productVersion: {{ .Chart.Version | quote }}
      labels:
        app: {{ template "skydive.fullname" . }}
        chart: {{ .Chart.Name | quote }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        tier: flow-exporter
    spec:
      dnsPolicy: ClusterFirstWithHostNet
{{- with .Values.flowExporter.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.flowExporter.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.flowExporter.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
{{- end }}
      {{- if and .Values.image.secretName (ne .Values.image.secretName "") }}
      imagePullSecrets:
      - name: {{ .Values.image.secretName | quote }}
      {{- end }}
      containers:
      - name: exporter
        image: "{{ .Values.flowExporter.image.repository }}:{{ .Values.flowExporter.image.tag }}"
        ports:
        - containerPort: 9100
          protocol: TCP
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
        env:
        - name: SKYDIVE_ANALYZERS
          value: "{{ template "skydive.fullname" . }}-analyzer.{{ .Release.Namespace }}.svc:{{ .Values.analyzer.service.port }}"
        - name: SKYDIVE_PIPELINE_SUBSCRIBER_URL
          value: "ws://{{ template "skydive.fullname" . }}-analyzer.{{ .Release.Namespace }}.svc:{{ .Values.analyzer.service.port }}/ws/subscriber/flow"
        - name: SKYDIVE_PIPELINE_STORE_BUFFERED_FILENAME_PREFIX
          valueFrom:
            configMapKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "objectPrefix"
        - name: SKYDIVE_PIPELINE_WRITE_S3_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "endpoint"
        - name: SKYDIVE_PIPELINE_WRITE_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "accesskey"
        - name: SKYDIVE_PIPELINE_WRITE_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "secretkey"
      {{- if .Values.flowExporter.write.s3.use_api_key }}
        - name: SKYDIVE_PIPELINE_WRITE_S3_API_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "apikey"
        - name: SKYDIVE_PIPELINE_WRITE_S3_IAM_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "iam_endpoint"
      {{- end }} 
        - name: SKYDIVE_PIPELINE_STORE_BUFFERED_DIRNAME
          valueFrom:
            configMapKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "bucket"
        - name: SKYDIVE_PIPELINE_WRITE_S3_REGION
          valueFrom:
            configMapKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "region"
        - name: SKYDIVE_PIPELINE_CLASSIFY_TYPE
          valueFrom:
            configMapKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "netmasksAutodiscoveryType"
        - name: SKYDIVE_PIPELINE_CLASSIFY_CLUSTER_NET_MASKS
          valueFrom:
            configMapKeyRef:
              name: "{{ template "skydive.fullname" . }}-flow-exporter"
              key: "netmasks"
      {{- with .Values.flowExporter.env_exporter }}
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
